spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intermediary_management
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:org/demo/mapper/xml/*.xml
logging:
  level:
    org.mybatis: DEBUG
